### ISSUE TITLE
Feature Request: tell which line is causing the error

### ISSUE THREAD

**Issue by igoracmelo** [Borvik/vscode-postgres#181]
In my case, where I have a bunch of "VALUES":
![image](https://user-images.githubusercontent.com/85039990/135280773-1d97225c-2451-4878-b338-041045770cee.png)

I can't really know which one is this error talking about:
![image](https://user-images.githubusercontent.com/85039990/135280487-6180408e-36ab-4b2e-91ba-7054d618ea7c.png)

**Comment by igoracmelo** [comment]
Ok, I just realized what was the mistake.
But anyways the feature request still valid.

**Comment by Borvik** [comment]
So all errors (whether the squiggles or during actual query running) come from the PostgreSQL server itself.  If PostgreSQL does not return positional data it can't be shown.

**Comment by Edzukins** [comment]
> So all errors (whether the squiggles or during actual query running) come from the PostgreSQL server itself. If PostgreSQL does not return positional data it can't be shown.

Postgres returns additional info for each error, exact querry part, position and other stuff, however extension shows only message part of error object, if you could change to show all object instead, that would be perfect.

**Comment by Borvik** [comment]
Not _always_... like I said, if it returns positional data, I attempt to use it.

Interesting that I tried replicating the type of the errors in the queries (multiple statements with no semi-colon to separate them, multiple `VALUES` keywords in a single statement, and missing commas between values) - and it did seem to highlight (granted it can only grab the _first_ error).

![image](https://user-images.githubusercontent.com/1764750/187657517-264107be-2f74-4588-80d4-eddbe8bf73e9.png)

What version of postgres are you connected to?

**Comment by Edzukins** [comment]
if we talk about highlighting it is not working for me, because I probably not doing something correctly.
When I open new query, everything is mostly fine, some simple errors it can show even before I run it:
![image](https://user-images.githubusercontent.com/81573103/187666863-8c34c523-4bf9-4b1d-9db5-13412fe2d3f6.png)
But once I save it (as .psql) then it does not work anymore
![image](https://user-images.githubusercontent.com/81573103/187666910-c93d85d1-7e04-4a26-9980-9cc75e9c966c.png)
Probobly problem is in some configuarion in my case. But anyway, if whole error object would be displayed, it would help in in some situations (not in this one, as there is only one '<' but in others), or at least to make message something like pgadmin:
![image](https://user-images.githubusercontent.com/81573103/187669442-41bbd812-09f4-4fe5-84ee-90eae06fc1d8.png)

My version is 13.6

**Comment by Borvik** [comment]
interesting... do you have any error logs for the postgres language service?

**Comment by Edzukins** [comment]
Any idea where to find them? Windows 10

**Comment by Borvik** [comment]
Output tab from vscode
![image](https://user-images.githubusercontent.com/1764750/187671600-e98945bf-3873-4072-a84f-5b3c42a1153f.png)

**Comment by Edzukins** [comment]
c:\...\.vscode\extensions\ckolkman.vscode-postgres-1.4.0\out\language\server.js:341
                        source: dbConnOptions.host
                                              ^

TypeError: Cannot read properties of null (reading 'host')
    at c:\...\.vscode\extensions\ckolkman.vscode-postgres-1.4.0\out\language\server.js:341:47
    at Generator.throw (<anonymous>)
    at rejected (c:\...\.vscode\extensions\ckolkman.vscode-postgres-1.4.0\out\language\server.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Info  - 2:03:01 PM] Connection to server got closed. Server will restart.
expected password response, got message type 88

**Comment by Borvik** [comment]
interesting.... based on that error it looks like the language server is losing connection in the middle of validating the statement.

Might be tricky to replicate, but maybe it has something to do with the act of saving the query clearing the connection.

**Comment by Edzukins** [comment]
I checked again, and problem why error (position) was not showing was because I just copied this query at end of other query without "; "
Once I separated them, it shows where error is (before I run it).
I guess this is just limitation that everyone need to understand when writing multiple separate queries in one file, and running only one of it by selection -it might not show error, if it is not separated from last query.
In pg_admin it will show error position and extra info no matter what is before that query, so this is not intuitive thing to think about when running querries.
