### ISSUE TITLE
Cannot read property 'metadata' of null

### ISSUE THREAD

**Issue by GammaGames** [Borvik/vscode-postgres#19]
I can still connect and view tables, views, and columns in each. However, when I try to run a query I get:

![image](https://user-images.githubusercontent.com/7832163/41115574-277f9f2a-6a45-11e8-8501-cb8d9c2cabc8.png)

This started after the latest update to vsc.

**Comment by GammaGames** [comment]
Here's the console output when I right click and pick "New Query":

```javascript
ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at PostgreSQLLanguageClient.setConnection (C:\Users\jlieberg\.vscode\extensions\ckolkman.vscode-postgres-1.0.9\out\language\client.js:27:108)
	at EditorState.onDidChangeActiveTextEditor (C:\Users\jlieberg\.vscode\extensions\ckolkman.vscode-postgres-1.0.9\out\common\editorState.js:43:29)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:784)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:727:112
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:330)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

And if I try to select the server from the toolbar it prints

```javascript
Cannot read property 'globalState' of null
```

Selecting a server in the explorer prints:

```javascript
error: Error: Running the contributed command:'vscode-postgres.setActiveConnection' failed. at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:709) at e.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:673:944) at e._executeConvertedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:676:388) at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:613) at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:675:6) at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832) at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550) at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631) at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400) at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315 at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395 at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432 at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764) at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338) at emitOne (events.js:96:13) at Socket.emit (events.js:191:7) at readableAddChunk (_stream_readable.js:178:18) at Socket.Readable.push (_stream_readable.js:136:10) at Pipe.onread (net.js:560:20)
exception: null
handler: undefined
id: 225
parent: undefined
promise: n.Class.derive._oncancel
__proto__: Object
```

**Comment by Borvik** [comment]
Interesting sometime this past week I updated vsc it on Ubuntu, but it continued working.

Just updated on my Windows box, and I do indeed see some of these error.

**Comment by Borvik** [comment]
Ok, this is weird.  It seems that `imports` from other files are now treated as if they are completely separate instances.  This is causing static members to be reset for each call.

It is possible this is a VSCode bug, will do some more digging for a solution.

**Comment by Borvik** [comment]
Ok, so I tried creating an example project that demonstrates this issue - and of course the _example_ works just fine.  I'm not entirely sure what's going on with these static members being lost in other imported files.

**Comment by GammaGames** [comment]
Still present in 1.24.1, darn!

**Comment by Borvik** [comment]
I was hoping... might have to go with a significant rewrite to try and find the underlying issue.

**Comment by GammaGames** [comment]
Have you made an issue on the vscode repo? They might be able to find the cause

**Comment by Borvik** [comment]
I started to create the example one to demonstrate the issue for just that purpose.  When that one worked fine - I'm not longer certain it is a vscode issue.
